name: Convert Quarto to Jupyter Notebook
on:
  push:
    branches:
      - main
    paths:
      - index.qmd
jobs:
  convert-qmd-into-ipynb:
    name: Convert Quarto to Jupyter Notebook
    runs-on: ubuntu-24.04
    steps:
      - name: Convert index.qmd
        uses: GESIS-Methods-Hub/qmd2ipynb@v2
        with:
          files: 'index.qmd'
          token: ${{ secrets.GITHUB_TOKEN }}