name: Convert Quarto to Jupyter Notebook
on:
  push:
    branches:
      - main
jobs:
  test-methods-hub-render:
    name: Convert Quarto to Jupyter Notebook
    steps:
      - name: Convert index.qmd
        uses: GESIS-Methods-Hub/qmd2ipynb@v2
        with:
          files: 'index.qmd'
          token: ${{ secrets.GITHUB_TOKEN }}